# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('data', jsonfield.fields.JSONField()),
            ],
        ),
    ]
